use of0.12.0

diff --git a/src/poco/release/script/mkdoc b/src/poco/release/script/mkdoc
--- a/src/poco/release/script/mkdoc
+++ b/src/poco/release/script/mkdoc
@@ -1,7 +1,5 @@
 #! /bin/sh
 #
-# $Id: //poco/1.4/release/script/mkdoc#2 $
-#
 # mkdoc
 #
 # Create reference documentation for a POCO release.
@@ -19,13 +17,21 @@ if [ "$POCO_BASE" = "" ] ; then
   exit 1
 fi
 
+osname=`uname -s | tr ' ' '_'`
+osarch=`uname -m | tr ' ' '_'`
+
+case `uname` in
+  CYGWIN*) osname="CYGWIN"
+            ;;
+esac
+
 spec=""
-docConfig=$POCO_BASE/PocoDoc/cfg/mkdoc-poco.xml
-while [ "$1" != "" ] ; 
+docConfig=""
+while [ "$1" != "" ] ;
 do
 	if [ "$1" = "-C" ] ; then
 		shift
-		docConfig=$1
+		docConfig="$docConfig -C $1"
 		shift
 	elif [ "$1" = "-v" ] ; then
 		shift
@@ -36,6 +42,10 @@ do
 		shift
 	fi
 done
+
+if [ -z "$docConfig" ] ; then
+	docConfig="-C $POCO_BASE/PocoDoc/cfg/mkdoc-poco.xml"
+fi
 
 if [ "$spec" != "" ] ; then
   relspec="-f release/spec/${spec}.release"
@@ -59,6 +69,14 @@ if [ "$version" = "" ] ; then
 fi
 release=$version$tag
 
+if [ ! -f libversion ] ; then
+  echo "Error: No libversion file found."
+  exit 2
+fi
+if [ "$libversion" = "" ] ; then
+	read libversion <$POCO_BASE/libversion
+fi
+
 #
 # Build release
 #
@@ -68,24 +86,27 @@ echo "Building tools"
 tools=$POCO_BASE/stage/tools
 rm -rf $tools
 mkdir -p $tools
-mkrelease -o $tools $version CppParser PocoDoc
+mkrelease -o $tools $version Data Data/SQLite CppParser PocoDoc
 
 cd $tools
-./configure --no-tests --no-samples
+./configure --no-tests --no-samples --no-prefix
 make -s -j8
+
+if [ $osname = "CYGWIN" ] ; then
+    find $tools -type f -name "cyg*$libversion.dll" > $TMP/dlls
+    rebase -O -T $TMP/dlls
+    rm $TMP/dlls
+fi
 
 cd $POCO_BASE
 
-osname=`uname -s | tr ' ' '_'`
-osarch=`uname -m | tr ' ' '_'`
-
-if [ $osname = "Darwin" ] ; then
-	archpath=`dirname stage/tools/PocoDoc/bin/Darwin/*/PocoDoc`
-	osarch=`basename $archpath`
+if [ $osname = "CYGWIN" ] ; then
+#   Poco dlls must be on PATH for Cygwin
+    export PATH=$tools/lib/$osname/$osarch:$PATH
 fi
 
 export PATH=$tools/PocoDoc/bin/$osname/$osarch:$PATH
 echo PATH=$PATH
 
 echo "Building documentation $release (using $docConfig)"
-mkdocumentation $reltag $relspec -C $docConfig -v $version
+mkdocumentation $reltag $relspec $docConfig -v $version
